version: "3"

services:
  app:
    build: .
    container_name: terea-stiki.ru # меняем на имя проекта
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=terea-stiki.ru # домен сайта
      - LETSENCRYPT_HOST=terea-stiki.ru # домен для SSL
      - LETSENCRYPT_EMAIL=qwe@email.com
    networks:
      - web

networks:
  web:
    external: true
